# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4995ea3c43bb538612da64610e0a62dff70b367ded2f56b3b2def2417c39ed7503924a738fa0d340f1e20e49fc40accbe56b4c300dc92fba02ed4ccb6372bcd1

test:
  secret_key_base: ae236b2a4c67e7c8ee2c19c665e226ac87af7b96cbe01a40648c161332d169745d812b56932a34c38d2a773855d09cdcab9dfdd734d9a76b612c2c0e4d7c2cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
